name: Haskell tests (mhs)

on: [push, pull_request]

env:
  MHS_VERSION: da363c44cd5d584f5938cae9a1b5ad81fc8fcdff

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache mhs build tools
        id: cache-mhs
        uses: actions/cache@v4
        with:
          path: ~/.mcabal/bin
          key: ${{ runner.os }}-mhs-$MHS_VERSION
      - name: Install mhs build tools
        if: steps.cache-mhs.outputs.cache-hit != 'true'
        run: |
          git clone --depth 1 https://github.com/augustss/MicroHs.git mhs
          cd mhs
          git fetch --depth 1 "${MHS_VERSION}"
          git checkout "${MHS_VERSION}"
          make minstall
      - name: Add bins to PATH
        run: echo "$HOME/.mcabal/bin" >> "$GITHUB_PATH"
      - name: Install package dependencies
        run: make mhs-deps
      - name: Run tests
        run: make mhs-test
